name: DS-geospatial
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter
  - jupyterlab
  - ipython
  - numpy
  - pandas
  - xarray
  - geopandas
  - rasterio
  - owslib
  - rasterstats
  - matplotlib
  - descartes
  - mapclassify
  - cartopy
  - contextily
  - geoplot
  - fsspec
  - s3fs
  - dask
  - distributed
  - intake
  - ipyleaflet
  - folium
