name: DS-geospatial
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipython
  - jupyter
  - jupyterlab>3
  - numpy
  - pandas
  - xarray
  - geopandas
  - rasterio
  - owslib
  - rasterstats
  - matplotlib
  - mapclassify
  - cartopy
  - contextily
  - geoplot
  - fsspec
  - s3fs
  - dask
  - distributed
  - dask-labextension
  - bokeh
  - jupyter_bokeh
  - intake
  - intake-xarray
  - ipympl
  - ipyleaflet
  - folium
  - seaborn
  - hvplot
  - geoviews
  - datashader
  - cmocean 
  - zarr
  - h5netcdf
  - h5py
  - cfgrib
  - pooch
  - rioxarray
  - xarray-spatial
  - pyepsg
