name: DS-geospatial
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipython
  - jupyter
  - jupyterlab>3
  - numpy
  - pandas
  - xarray=2022.09
  - geopandas
  - pygeos
  - rasterio
  - owslib
  - rasterstats
  # pinning to avoid compat issue with cartopy (https://github.com/jorisvandenbossche/course-python-geospatial/issues/21)
  - matplotlib=3.5
  - mapclassify
  - cartopy
  - contextily
  - geoplot
  - fsspec
  - s3fs
  - dask
  - distributed
  - dask-labextension
  - bokeh
  - jupyter_bokeh
  - intake
  - intake-xarray
  - ipympl
  - ipyleaflet
  - folium
  - seaborn
  - hvplot
  - geoviews
  - datashader
  - cmocean
  - pygeoprocessing
  - zarr
  - h5netcdf
  - h5py
  - cfgrib
  - pooch
  - rioxarray
  - xarray-spatial
  - pyepsg
