name: DS-geospatial
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter
  - jupyterlab
  - ipython
  - numpy
  - pandas
  - xarray
  - geopandas
  - pygeos
  - rasterio
  - owslib
  - rasterstats
  - matplotlib
  - descartes
  - mapclassify
  - cartopy
  - contextily
  - geoplot
  - fsspec
  - s3fs
  - dask
  - distributed
  - bokeh
  - intake
  - intake-xarray
  - ipyleaflet
  - folium
  - seaborn
  - hvplot
  - geoviews
  - datashader
  - pygeoprocessing
  - zarr
  - h5netcdf
  - h5py
  - rioxarray
  - xarray-spatial
